// export { default as Gallery } from "./Gallery";
// export { default as Article } from "./Article";
// export { default as ArticlePWA } from "./PWA/ArticlePWA";
// export { default as HomePWA } from "./PWA/HomePWA";
// export { default as Video } from "./Video";
// export { default as NotFound } from "./NotFound";
// export { default as ArticleAMP } from "./AMP/ArticleAMP";
// export { default as Author } from "./Author";
// export { default as Error404 } from "./Error404";
// export { default as Search } from "./Search";
export { default as Match } from "./Match";
export { default as Home } from "./Home";
export { default as Tournament } from "./Tournament";
export { default as Sports } from "./Sports";
